project:
  type: website

website:
  title: "Open Scholarship Community Sheffield Launch"
  site-url: https://github.com/ns-rse/openfest2023-oscsheffield
  description: "Quarto RevealJS slides for Open Scholarship Community Sheffield Launch at OpenFest2023"
